version: '3.1'

volumes:
  postgres-data:

services:
  pg:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: simple-graphql-chat
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata:z'
    ports:
      - '5432:5432'
